
variable "accesskey" {
  type = string
}

variable "secretkey" {
  type = string
}

data "amazon-ami" "autogenerated_1" {
  access_key = "${var.accesskey}"
  filters = {
    name                = "ubuntu/images/*ubuntu-xenial-16.04-amd64-server-*"
    root-device-type    = "ebs"
    virtualization-type = "hvm"
  }
  most_recent = true
  owners      = ["099720109477"]
  region      = "us-east-1"
  secret_key  = "${var.secretkey}"
}

source "amazon-ebs" "autogenerated_1" {
  access_key                  = "${var.accesskey}"
  ami_name                    = "samim-ami-java-tomcat2"
  associate_public_ip_address = "true"
  instance_type               = "t3.micro"
  region                      = "us-east-1"
  secret_key                  = "${var.secretkey}"
  security_group_id           = "sg-0585839a0077faf5a"
  source_ami                  = "${data.amazon-ami.autogenerated_1.id}"
  ssh_keypair_name            = "consul"
  ssh_private_key_file        = "consul.pem"
  ssh_username                = "ubuntu"
}

build {
  sources = ["source.amazon-ebs.autogenerated_1"]

  provisioner "shell" {
    inline = ["sudo add-apt-repository ppa:openjdk-r/ppa", "sudo apt-get update", "sudo apt-get install -y openjdk-8-jdk", "java -version", "sudo apt-get install -y tomcat8"]
  }

}
